services:
  mongo-db-service:
    container_name: mongo-db
    image: mongo:4.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=auth
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  drum-beat-repo-app-service:
    container_name: drum-beat-repo-app
    image: drum-beat-repo-app-image
    env_file:
      - .env
    ports:
      - "9000:9000"
    depends_on:
      mongo-db-service:
        condition: service_healthy

volumes:
  mongo-data: